// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageRequest {
    #[prost(enumeration = "Flip", tag = "1")]
    pub flip: i32,
    #[prost(enumeration = "Size", tag = "2")]
    pub thumb_size: i32,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub jpeg_sidecar: bool,
    #[prost(bool, tag = "5")]
    pub force_libraw: bool,
    #[prost(uint32, tag = "6")]
    pub request_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageResponse {
    #[prost(uint32, tag = "1")]
    pub request_id: u32,
    #[prost(enumeration = "ResponseCode", tag = "2")]
    pub response_code: i32,
    #[prost(enumeration = "ImageType", tag = "3")]
    pub image_type: i32,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Flip flip = 1;
    /// Size thumb_size = 2;
    /// string path = 3;
    /// bool jpeg_sidecar = 4;
    /// bool force_libraw = 5;
    /// bool request_id = 6;
    #[prost(uint32, tag = "5")]
    pub content_length: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Flip {
    DefaultFlip = 0,
    Upright = 1,
    Rotated90 = 2,
    Rotated180 = 3,
    Rotated270 = 4,
}
impl Flip {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DefaultFlip => "DefaultFlip",
            Self::Upright => "Upright",
            Self::Rotated90 => "Rotated90",
            Self::Rotated180 => "Rotated180",
            Self::Rotated270 => "Rotated270",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DefaultFlip" => Some(Self::DefaultFlip),
            "Upright" => Some(Self::Upright),
            "Rotated90" => Some(Self::Rotated90),
            "Rotated180" => Some(Self::Rotated180),
            "Rotated270" => Some(Self::Rotated270),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Size {
    DefaultSize = 0,
    Low = 1,
    Mid = 2,
    High = 3,
}
impl Size {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DefaultSize => "DefaultSize",
            Self::Low => "Low",
            Self::Mid => "Mid",
            Self::High => "High",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DefaultSize" => Some(Self::DefaultSize),
            "Low" => Some(Self::Low),
            "Mid" => Some(Self::Mid),
            "High" => Some(Self::High),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResponseCode {
    DefaultResponseCode = 0,
    Success = 1,
    NotFound = 2,
    Failed = 3,
}
impl ResponseCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DefaultResponseCode => "DefaultResponseCode",
            Self::Success => "Success",
            Self::NotFound => "NotFound",
            Self::Failed => "Failed",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DefaultResponseCode" => Some(Self::DefaultResponseCode),
            "Success" => Some(Self::Success),
            "NotFound" => Some(Self::NotFound),
            "Failed" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ImageType {
    DefaultImageType = 0,
    Jpeg = 1,
    Png = 2,
    Raw = 3,
}
impl ImageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DefaultImageType => "DefaultImageType",
            Self::Jpeg => "Jpeg",
            Self::Png => "Png",
            Self::Raw => "Raw",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DefaultImageType" => Some(Self::DefaultImageType),
            "Jpeg" => Some(Self::Jpeg),
            "Png" => Some(Self::Png),
            "Raw" => Some(Self::Raw),
            _ => None,
        }
    }
}
